### ISSUE TITLE
inspector对应weexSDK的版本，不能说明清楚吗？

### ISSUE THREAD

**Issue by mario-huang** [weexteam/android-devtools-for-Apache-Weex#65]

**Comment by ccfish86** [comment]
又是一个KPI工程，阿里特色

**Comment by ccfish86** [comment]
不过我翻遍了`http://jcenter.bintray.com` 还是找到了那个类，多引一个[inspector](http://jcenter.bintray.com/com/taobao/android/inspector/0.0.2.1/)就可以了。
